### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by plusczh** [szagoruyko/pytorchviz#7]
File "F:\Anaconda3\lib\site-packages\torchviz\dot.py", line 38, in add_nodes
    if var not in seen:
TypeError: unhashable type: 'list'

**Comment by DoHoNi** [comment]
I got similar issue. 
How do you solve it?

```python
x = torch.randn(1,3,640,640)
model = model.float()
make_dot(model(x), params=params).render("graph", format="png")
```

-------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 17, in <module>
    make_dot(model(x), params=dict(model.named_parameters())).render("graph", format="png")
  File "/opt/conda/lib/python3.8/site-packages/torchviz/dot.py", line 161, in make_dot
    add_base_tensor(v)
  File "/opt/conda/lib/python3.8/site-packages/torchviz/dot.py", line 146, in add_base_tensor
    if var in seen:
TypeError: unhashable type: 'list'
