### ISSUE TITLE
AttributeError in make_dot with GNN from dgl.ai

### ISSUE THREAD

**Issue by Galvalon** [szagoruyko/pytorchviz#75]
Hi,
i get _AttributeError: 'NoneType' object has no attribute 'size'_ when calling make_dot on a model with Graph Layers from dgl.ai.

Traceback (most recent call last):
  File "/home/procon/PycharmProjects/pythonProject/dgl_demo.py", line 34, in <module>
    make_dot(yhat, params=dict(list(model.named_parameters()))).render("dgl_torchviz", format="png")
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 164, in make_dot
    add_base_tensor(var)
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 152, in add_base_tensor
    add_nodes(var.grad_fn)
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 134, in add_nodes
    add_nodes(u[0])
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 134, in add_nodes
    add_nodes(u[0])
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 134, in add_nodes
    add_nodes(u[0])
  [Previous line repeated 6 more times]
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 143, in add_nodes
    dot.node(str(id(t)), get_var_name(t), fillcolor='orange')
  File "/home/procon/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/torchviz/dot.py", line 94, in get_var_name
    return '%s\n %s' % (name, size_to_str(var.size()))
AttributeError: 'NoneType' object has no attribute 'size'

I managed to find the Error in <torch.autograd.function.GSpMMBackward object at 0x7f9967e3d3c0>.saved_tensors:
(tensor([[-0.0195, -0.0067,  0.0089,  ...,  0.0059,  0.0044,  0.0048],
        [-0.0109, -0.0004, -0.0014,  ...,  0.0007, -0.0025,  0.0068],
        [-0.0029,  0.0007, -0.0012,  ...,  0.0047, -0.0005, -0.0004],
        ...,
        [-0.0080,  0.0008,  0.0103,  ..., -0.0114,  0.0148, -0.0007],
        [-0.0051,  0.0026, -0.0093,  ...,  0.0029, -0.0049,  0.0003],
        [-0.0041,  0.0019, -0.0016,  ..., -0.0011,  0.0051, -0.0004]],
       grad_fn=<MmBackward>), None, None, None)

As add_nodes in dot.py should just ignore those None objects, a simple fix would be
      if hasattr(fn, 'saved_tensors'):
          for t in fn.saved_tensors:
              **if t is not None:**
                  dot.edge(str(id(t)), str(id(fn)))
                  dot.node(str(id(t)), get_var_name(t), fillcolor='orange')
added in dot.py line 139-143

If there is any other error please let me know or reach out, i am just using a basic example for a GNN
        class GCN(nn.Module):
            def __init__(self, in_feats, hidden_size, num_classes):
                super(GCN, self).__init__()
                self.conv1 = GraphConv(in_feats, hidden_size)
                self.conv2 = GraphConv(hidden_size, num_classes)
        
            def forward(self, g, inputs):
                h = self.conv1(g, inputs)
                h = torch.relu(h)
                h = self.conv2(g, h)
                return h
from https://docs.dgl.ai/en/0.5.x/tutorials/basics/1_first.html#step-3-define-a-graph-convolutional-network-gcn

**Comment by Galvalon** [comment]
Just saw the latest Pull Request for this specific issue
